### ISSUE TITLE
regression loss

### ISSUE THREAD

**Issue by mmr12** [mmr12/DeepBlueSea#5]
To calculate the regression loss, we need:
1) the anchor class
2) if the anchor class is positive, we need to know which boat it relates to, and then calculate the difference in centre, height and width between the gt and the anchor, and the prediction and the anchor

So far I have done the following:
- data generator passes the centre, width and height of the boxes onto y_reg
- y_reg_boat tells (gives the index) which boat corresponds to which positively classified anchor
 - t_x, .. , t_h_star are the values we will calculate the loss on (see paper for deets)

the model builds, I haven't checked if 

TODO:
- I have written a code in numpy to use the indexing from y_reg_boat and apply it to y_reg, we need to make it tensorflow compatible 
- put together t_x,...,t_h_star into a tensor to calculate the loss
- multiply the latter tensor by the classification vector (only look at positive boxes)

(more optional): I do some calculations on the anchors that don't need to be done at every iteration (calculate the centre, height etc), maybe theres a better place to put the code?

**Comment by brian-regan** [comment]
Just looking at this it seems youve implemented the "tensor-ification" of the calculation of the t and the t stars. Just looks like a loss calculation needs to be done. Correct?

**Comment by brian-regan** [comment]
> (more optional): I do some calculations on the anchors that don't need to be done at every iteration (calculate the centre, height etc), maybe theres a better place to put the code?

this seems okay as is tbh. Dont see it slowing things down significantly
